apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: |-
    {{ tpl (.Files.Get "files/config.yaml") . | b64enc | nindent 4 }}