name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-app:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build app
        run: go build -v ./...

      - name: Test app
        run: go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-api-server-example:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/go-api-server-example:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/go-api-server-example:buildcache,mode=max

      - name: Helm Deploy
        uses: vimeda/helm@v1.6.8
        with:
          helm: 'helm3'
          release: 'go-server'
          namespace: 'default'
          chart: './.chart'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'


#  test-app:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.18
#
#      - name: Test
#        run: go test -v ./...
#
#  build-image:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./.docker/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-api-server-example:latest
#          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/go-api-server-example:buildcache
#          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/go-api-server-example:buildcache,mode=max
#
#  deploy-app:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Helm Deploy
#        uses: vimeda/helm@v1.6.8
#        with:
#          helm: 'helm3'
#          release: 'go-server'
#          namespace: 'default'
#          chart: './.chart'
#        env:
#          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'