name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-api-server-example:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/go-api-server-example:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/go-api-server-example:buildcache,mode=max

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Helm Deploy
        uses: vimeda/helm@v1.6.8
        with:
          helm: 'helm3'
          release: 'test'
          namespace: 'default'
          chart: './.chart'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

